version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: murino
      POSTGRES_USER: murino
      POSTGRES_PASSWORD: murino
    ports:
      - "5432:5432"
    volumes:
      - ./golang.sql:/docker-entrypoint-initdb.d/init.sql
